"""Core quantum game primitives for Axelrod-style IPD simulations.

The module implements an Eisert-Wilkens-Lewenstein (EWL) inspired
quantization. Classical policies choose C or D; a configurable execution layer
maps these symbols to single-qubit unitaries. The default ``classical`` lift is
included as a control condition: without noise it reproduces the classical IPD
for any entanglement value because the classical operations commute with the
EWL entangler. Non-classical phase lifts are therefore required for an
entanglement-dependent strategic effect.
"""
from __future__ import annotations

from dataclasses import dataclass
from functools import reduce
from typing import Iterable, Sequence

import numpy as np

Array = np.ndarray

I2: Array = np.eye(2, dtype=complex)
X: Array = np.array([[0, 1], [1, 0]], dtype=complex)
Y: Array = np.array([[0, -1j], [1j, 0]], dtype=complex)
Z: Array = np.array([[1, 0], [0, -1]], dtype=complex)
# EWL defection operator generated by the U(theta, phi) parameterization.
D_EWL: Array = np.array([[0, 1], [-1, 0]], dtype=complex)  # equivalent to i*sigma_y


def kron_all(ops: Iterable[Array]) -> Array:
    """Kronecker product over a non-empty iterable of matrices."""
    ops = list(ops)
    if not ops:
        raise ValueError("kron_all requires at least one operator")
    return reduce(np.kron, ops)


def ewl_unitary(theta: float, phi: float) -> Array:
    """Return the one-qubit EWL strategy U(theta, phi).

    U(0, 0) is cooperation and U(pi, 0) is the conventional EWL defection.
    """
    c = np.cos(theta / 2.0)
    s = np.sin(theta / 2.0)
    return np.array(
        [[np.exp(1j * phi) * c, s], [-s, np.exp(-1j * phi) * c]],
        dtype=complex,
    )


def action_unitary(action: str, lift: str = "classical", phase: float = np.pi / 2) -> Array:
    """Map a C/D action to a quantum execution unitary.

    Parameters
    ----------
    action:
        Either ``"C"`` or ``"D"``.
    lift:
        ``"classical"`` uses C=I and D=U(pi,0). ``"phase"`` maps cooperation
        to Q=U(0, phase) while retaining D=U(pi,0). ``"mixed_phase"`` maps C to
        U(0, phase) and D to U(pi, phase/2).
    phase:
        Coherent phase used by the non-classical lifts.
    """
    action = action.upper()
    if action not in {"C", "D"}:
        raise ValueError(f"unknown action {action!r}; expected 'C' or 'D'")
    if lift == "classical":
        return ewl_unitary(0.0, 0.0) if action == "C" else ewl_unitary(np.pi, 0.0)
    if lift == "phase":
        return ewl_unitary(0.0, phase) if action == "C" else ewl_unitary(np.pi, 0.0)
    if lift == "mixed_phase":
        return ewl_unitary(0.0, phase) if action == "C" else ewl_unitary(np.pi, phase / 2.0)
    raise ValueError(f"unknown lift {lift!r}")


def entangler(n_players: int, gamma: float) -> Array:
    """Return the n-player GHZ-type EWL entangler.

    J_n(gamma) = exp(i gamma D^{otimes n}/2) = cos(gamma/2) I + i sin(gamma/2)D^{otimes n},
    where D=U(pi,0). The construction reduces to the standard two-player EWL
    entangler and avoids the common error of applying a ZZ phase to |0...0>,
    which only adds a global phase and does not entangle the state.
    """
    if n_players < 2:
        raise ValueError("at least two players are required")
    dim = 2**n_players
    A = kron_all([D_EWL for _ in range(n_players)])
    return np.cos(gamma / 2.0) * np.eye(dim, dtype=complex) + 1j * np.sin(gamma / 2.0) * A


def local_operator(unitaries: Sequence[Array]) -> Array:
    """Tensor product of local strategy unitaries."""
    return kron_all(unitaries)


def initial_state(n_players: int) -> Array:
    """Computational-basis |00...0> state vector."""
    psi = np.zeros(2**n_players, dtype=complex)
    psi[0] = 1.0
    return psi


def ket_to_rho(psi: Array) -> Array:
    """Convert a state vector to a density matrix."""
    return np.outer(psi, np.conjugate(psi))


def single_qubit_operator(op: Array, target: int, n_players: int) -> Array:
    """Embed a one-qubit operator at ``target`` in an n-qubit Hilbert space."""
    if target < 0 or target >= n_players:
        raise ValueError("target qubit out of range")
    return kron_all([op if i == target else I2 for i in range(n_players)])


def apply_bit_flip(rho: Array, p: float, n_players: int) -> Array:
    """Apply an independent bit-flip channel to each qubit."""
    out = rho
    for i in range(n_players):
        Xi = single_qubit_operator(X, i, n_players)
        out = (1 - p) * out + p * Xi @ out @ Xi.conj().T
    return out


def apply_depolarizing(rho: Array, p: float, n_players: int) -> Array:
    """Apply an independent depolarizing channel to each qubit."""
    out = rho
    for i in range(n_players):
        acc = np.zeros_like(out)
        for pauli in (X, Y, Z):
            Pi = single_qubit_operator(pauli, i, n_players)
            acc += Pi @ out @ Pi.conj().T
        out = (1 - p) * out + (p / 3.0) * acc
    return out


def outcome_probabilities(
    unitaries: Sequence[Array],
    gamma: float,
    noise: float = 0.0,
    noise_model: str = "none",
) -> Array:
    """Return computational-basis outcome probabilities for one quantum stage."""
    n = len(unitaries)
    J = entangler(n, gamma)
    U = local_operator(unitaries)
    psi = U @ (J @ initial_state(n))
    rho = ket_to_rho(psi)
    if noise > 0:
        if noise_model == "bit_flip":
            rho = apply_bit_flip(rho, noise, n)
        elif noise_model == "depolarizing":
            rho = apply_depolarizing(rho, noise, n)
        elif noise_model in {"none", None}:
            pass
        else:
            raise ValueError(f"unknown noise model {noise_model!r}")
    rho = J.conj().T @ rho @ J
    probs = np.real(np.diag(rho))
    probs = np.maximum(probs, 0.0)
    probs = probs / probs.sum()
    return probs


@dataclass(frozen=True)
class PayoffMatrix:
    """Classical Prisoner's Dilemma payoff matrix."""

    T: float = 5.0
    R: float = 3.0
    P: float = 1.0
    S: float = 0.0

    def validate(self) -> None:
        if not (self.T > self.R > self.P > self.S):
            raise ValueError("PD payoffs must satisfy T > R > P > S")


def bits_from_index(index: int, n_players: int) -> tuple[int, ...]:
    """Return computational-basis bits for an index, with 0=C and 1=D."""
    return tuple(int(b) for b in format(index, f"0{n_players}b"))


def payoff_for_outcome(bits: Sequence[int], payoff: PayoffMatrix = PayoffMatrix()) -> Array:
    """Pairwise-additive n-player IPD payoff for a measured outcome.

    Each player's payoff is averaged over all pairwise interactions with the
    other players. For n=2 this is exactly the standard Prisoner's Dilemma.
    """
    payoff.validate()
    n = len(bits)
    scores = np.zeros(n, dtype=float)
    for i in range(n):
        for j in range(n):
            if i == j:
                continue
            if bits[i] == 0 and bits[j] == 0:
                scores[i] += payoff.R
            elif bits[i] == 0 and bits[j] == 1:
                scores[i] += payoff.S
            elif bits[i] == 1 and bits[j] == 0:
                scores[i] += payoff.T
            else:
                scores[i] += payoff.P
    return scores / (n - 1)


def expected_payoffs(
    unitaries: Sequence[Array],
    gamma: float,
    noise: float = 0.0,
    noise_model: str = "none",
    payoff: PayoffMatrix = PayoffMatrix(),
) -> Array:
    """Expected payoff vector for one quantum stage."""
    n = len(unitaries)
    probs = outcome_probabilities(unitaries, gamma, noise, noise_model)
    exp = np.zeros(n, dtype=float)
    for idx, prob in enumerate(probs):
        exp += prob * payoff_for_outcome(bits_from_index(idx, n), payoff)
    return exp


def sample_outcome(probs: Array, rng: np.random.Generator) -> tuple[int, tuple[int, ...]]:
    """Sample a computational-basis outcome from a probability vector."""
    idx = int(rng.choice(len(probs), p=probs))
    n = int(np.log2(len(probs)))
    return idx, bits_from_index(idx, n)
